######################################################################
# Automatically generated by qmake (2.00a) Wed Sep 20 04:34:39 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += . \
              pluginManager \
              templates/DockableFeatures \
              templates/DockablePluginManager \
              templates/DockItemFeatures \
              templates/PluginFeatures
INCLUDEPATH += . \
               pluginManager \
               templates/DockablePluginManager \
               templates/DockableFeatures \
               templates/DockItemFeatures \
               templates/PluginFeatures

# Input
HEADERS += pluginManager/pluginManager.h \
           templates/DockableFeatures/dockableFeatures.h \
           templates/DockablePluginManager/dockablePluginManager.h \
           templates/DockItemFeatures/dockItemFeatures.h \
           templates/PluginFeatures/pluginFeatures.h
SOURCES += main.cpp \
           pluginManager/pluginManager.cpp \
           templates/DockItemFeatures/dockItemFeatures.cpp \
           templates/PluginFeatures/pluginFeatures.cpp
